version: '2'

services:
    mongo-express:
        image: autopilotpattern/mongo-express
        restart: always
        mem_limit: "512m"
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            # ME_CONFIG_MONGODB_SERVER will get re-written by consul-template
            - ME_CONFIG_MONGODB_SERVER=mongodb
        labels:
            - triton.cns.services=mongo-express
        network_mode: bridge
        env_file: _env
        ports:
          - 8081
    mongodb:
        extends:
            file: local-compose.yml
            service: mongodb
        mem_limit: 4g
        labels:
            - triton.cns.services=mongod
        network_mode: bridge
        env_file: _env
    consul:
        extends:
            file: local-compose.yml
            service: consul
        labels:
            - triton.cns.services=consul
        network_mode: bridge
